### ISSUE TITLE
.DS_Store files

### ISSUE THREAD

**Issue by Noviel** [SoMaad/project-2#1]
* [x] Investigate what is `.DS_Store` files.
* [x] Выяснить, нужно ли файла такого типа добавлять в git.

В случае, если не нужно:
* [x] Удалить все `.DS_Store` файлы из репозитория и предотвратить их дальнейшее появление:
  * [x] узнать про `.gitignore` файл
  * [x] узнать необходимые для удаления git комманды, либо интерфейсные средства

**Comment by SoMaad** [comment]
done in this commit 87c3f0e165d2d38ca7933ba962bca452c29d933c

**Comment by Noviel** [comment]
Nice!
